/* Zona Caliente Pro: rendered from meeting records, never from social artwork. */
const root = document.getElementById('main');
const $ = (s) => document.querySelector(s);
const route = () => new URLSearchParams(location.search).get('ruta') || location.pathname;
const esc = (value) => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dateES = (date) => new Intl.DateTimeFormat('es-VE',{weekday:'long',day:'numeric',month:'long,',year:'numeric'}).format(new Date(`${date}T12:00:00`)).toUpperCase();
const combinations = (legs) => Object.values(legs).reduce((n, picks) => n * picks.length, 1);
const link = (path, text, className = '') => `<a class="${className}" href="${path}" data-route>${text}</a>`;
function state(m) { return `<span class="status">${esc(m.status)}</span>`; }
function shell(title, eyebrow, body) { return `<section class="section"><div class="wrap"><div class="heading"><div><div class="eyebrow">${eyebrow}</div><h2>${title}</h2></div></div>${body}</div></section>`; }
function meetingTitle(m) { return `${esc(m.track)} — REUNIÓN ${m.meeting_number} — ${dateES(m.date)}`; }
function gateReady(m) { return Object.values(m.gate).every(Boolean); }
function meetingCard(m) { return `<article class="meeting"><div><div class="eyebrow">PRÓXIMA REUNIÓN · ${esc(m.status)}</div><h2>${meetingTitle(m)}</h2><p class="muted">Información nativa, editable y trazable. El análisis se publicará tras validar el gate pre-carrera.</p></div>${link(`/reuniones/${m.slug}`,'VER REUNIÓN','btn')}</article>`; }
function home(meetings) {
 const current = meetings.find(m => m.status !== 'FINALIZADA') || meetings[0];
 root.innerHTML = `<section class="hero"><div class="wrap"><div class="eyebrow">ANÁLISIS · ESTRATEGIA · DATOS · RESULTADOS</div><h1>ZONA<br><em>CALIENTE</em> PRO</h1><p>Pronósticos hípicos con análisis, estrategia y resultados.</p><div class="actions">${link(`/reuniones/${current.slug}`,'VER PRONÓSTICOS DE HOY','btn')}${link(`/reuniones/${current.slug}#cuadro`,'VER CUADRO PERFECTO','btn alt')}</div></div></section>${shell('La jornada disponible','REUNIÓN DEL DÍA',meetingCard(current))}${shell('Inteligencia que se puede verificar','EL PRODUCTO',`<div class="grid"><article class="card"><div class="label">01</div><h3>Análisis de carrera</h3><p>Favorito, enemigo, sorpresa y base ordenados por carrera, no escondidos en una imagen.</p></article><article class="card"><div class="label">02</div><h3>Cuadro Perfecto 5y6</h3><p>Presentado, Recomendado y Premium con combinaciones y sellado sólo cuando exista el valor oficial.</p></article><article class="card"><div class="label">03</div><h3>Resultados reales</h3><p>El pronóstico pre-carrera se conserva como snapshot para medir el rendimiento sin reescribir el historial.</p></article></div>`)}`;
}
function races(m, kind) { const list=m.races.filter(r=>r.kind===kind); return list.map(r=>`<article class="race"><strong>${esc(r.public_label)}</strong><p>${r.distance||'Distancia por confirmar'}<br>${r.time||'Hora por confirmar'}</p>${r.horses.length?`<p>${r.horses.map(h=>`#${esc(h.number)} ${esc(h.name)}`).join('<br>')}</p>`:'<p>Nómina y análisis pendientes de fuente oficial.</p>'}</article>`).join(''); }
function ticket(t, unit) { const total = combinations(t.legs); const ready=Object.values(t.legs).every(x=>x.length); const tier=t.tier==='RECOMENDADO'?' recomendado':''; return `<article class="ticket${tier}"><div class="label">CUADRO ${esc(t.tier)}</div><h3>5Y6</h3><div class="legs">${Object.entries(t.legs).map(([leg,picks])=>`<div class="leg"><b>${leg}</b> · ${picks.length?picks.map(esc).join(', '):'—'}</div>`).join('')}</div><div class="total">TOTAL DE COMBINACIONES<br><span>${ready?total:'Pendiente de selección'}</span>${ready&&unit!==null?`<br><small>MONTO DE SELLADO: ${total*unit}</small>`:''}${ready&&unit===null?'<br><small>Valor oficial de unidad pendiente</small>':''}</div></article>`; }
function meeting(m) {
 const gate = Object.entries(m.gate).map(([key,done])=>`<div class="${done?'done':'todo'}">${done?'✓':'○'} ${key.replaceAll('_',' ')}</div>`).join('');
 const empty = '<div class="empty">Aún no hay datos publicados para este módulo. Se mostrará información verificada, no estimaciones inventadas.</div>';
 root.innerHTML = `<section class="section"><div class="wrap"><div class="heading"><div><div class="eyebrow">REUNIÓN DEL DÍA</div><h2>${meetingTitle(m)}</h2></div>${state(m)}</div><p class="callout">Estado: <b>${gateReady(m)?'LISTO PARA SELLAR':esc(m.status)}</b>. La reunión no se presenta como lista para sellar hasta completar el gate.</p></div></section>${shell('Gate pre-carrera','VALIDACIÓN',`<div class="gate">${gate}</div>`)}${shell('No válidas — 1C a 8C','CARRERAS',`<div class="race-grid">${races(m,'NO_VALIDA')}</div>`)}${shell('5y6 — 1V a 6V','CARRERAS',`<div class="race-grid">${races(m,'5Y6')}</div>`)}<section id="cuadro" class="section dark"><div class="wrap"><div class="heading"><div><div class="eyebrow">CUADRO PERFECTO</div><h2>5Y6</h2></div></div><div class="tickets">${m.tickets.map(t=>ticket(t,m.unit_value)).join('')}</div></div></section>${shell('Inteligencia de la jornada','SEÑALES',`<div class="grid"><article class="card"><h3>BASES DEL DÍA</h3>${m.intelligence.bases.length?m.intelligence.bases.map(esc).join('<br>'):empty}</article><article class="card"><h3>BOMBAS Y BATACAZOS</h3>${m.intelligence.bombas.length?m.intelligence.bombas.map(esc).join('<br>'):empty}</article><article class="card"><h3>CARRERA TRAMPA · ALERTAS · RETIRADOS</h3>${m.intelligence.carrera_trampa?esc(m.intelligence.carrera_trampa):empty}</article></div>`)}${shell('Registro y resultado','TRAZABILIDAD',m.results?'<p>Resultados oficiales disponibles.</p>':empty)}`;
}
function archive(meetings) { root.innerHTML=shell('Archivo de reuniones','REUNIONES',`<div class="grid">${meetings.map(m=>`<article class="card"><div class="label">${esc(m.status)}</div><h3>${meetingTitle(m)}</h3><p>Snapshot: ${m.published_snapshot_at||'Sin publicar'}</p>${link(`/reuniones/${m.slug}`,'ABRIR REUNIÓN','btn alt')}</article>`).join('')}</div>`); }
function results(meetings) { const completed=meetings.filter(m=>m.results); root.innerHTML=shell('Resultados y rendimiento','RESULTADOS',completed.length?`<table class="table"><thead><tr><th>Reunión</th><th>Favorito</th><th>Cuadros</th></tr></thead><tbody>${completed.map(m=>`<tr><td>${meetingTitle(m)}</td><td>${esc(m.results.favorite_accuracy||'—')}</td><td>${esc(m.results.ticket_performance||'—')}</td></tr>`).join('')}</tbody></table>`:'<div class="empty"><b>Historial en construcción.</b><br>No existe información histórica suficiente en el nuevo modelo para calcular métricas sin fabricar datos.</div>'); }
function render(meetings) { const p=route().replace(/\/$/,'')||'/'; const slug=p.match(/^\/reuniones\/([^/]+)$/)?.[1]; const found=meetings.find(m=>m.slug===slug); if(p==='/')home(meetings); else if(p==='/reuniones')archive(meetings); else if(p==='/resultados')results(meetings); else if(found)meeting(found); else root.innerHTML=shell('Ruta no encontrada','404',link('/','VOLVER AL INICIO','btn')); document.title = found?`${found.track} R${found.meeting_number} | Zona Caliente Pro`:'Zona Caliente Pro | Cuadro Perfecto'; document.querySelectorAll('[data-route]').forEach(a=>a.addEventListener('click',e=>{if(e.metaKey||e.ctrlKey)return;e.preventDefault();history.pushState({},'',a.getAttribute('href'));render(meetings);window.scrollTo(0,0)})); document.querySelectorAll('#nav a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')===p)); }
$('#menu').addEventListener('click',()=>$('#nav').classList.toggle('open'));
window.addEventListener('popstate',()=>fetch('/data/meetings.json').then(r=>r.json()).then(x=>render(x.meetings)));
fetch('/data/meetings.json').then(r=>{if(!r.ok)throw new Error('No se pudo cargar el registro');return r.json()}).then(x=>render(x.meetings)).catch(()=>root.innerHTML='<div class="wrap section"><div class="empty">No se pudo cargar la reunión. Intente nuevamente.</div></div>');
