const assert=require('node:assert/strict');
const model=require('../js/jornada-model.js');
const {selectCurrentMeeting}=require('../js/meeting-selection.js');
const {applyEvent}=require('../scripts/jornada-agent.cjs');
const fs=require('node:fs');
const meetings=JSON.parse(fs.readFileSync('data/meetings.json')).meetings;
const snapshots=JSON.parse(fs.readFileSync('data/analysis-snapshots.json')).snapshots;
const valencia=meetings.find(m=>m.track==='Valencia'), rinconada=meetings.find(m=>m.track==='La Rinconada');
assert.equal(selectCurrentMeeting(meetings,new Date('2026-09-18T12:00:00Z')).id,valencia.id);
assert.equal(selectCurrentMeeting([rinconada],new Date('2026-09-18T12:00:00Z')).id,rinconada.id);
assert.equal(selectCurrentMeeting(meetings,new Date('2026-09-20T02:00:00Z')).id,valencia.id);
assert.equal(selectCurrentMeeting(meetings,new Date('2026-09-20T12:00:00Z')).id,rinconada.id);
assert.equal(selectCurrentMeeting([]),null);
assert.equal(model.combinations({}),null);
assert.equal(model.combinations({a:[1],b:[1],c:[1],d:[1],e:[1],f:[]}),null);
assert.equal(model.combinations(rinconada.tickets.find(t=>t.tier==='RECOMENDADO').legs),288);
assert.equal(model.safeURL('javascript:alert(1)'),null);
const race=rinconada.races[0];
const base={meeting_id:rinconada.id,race_id:race.id,type:'result',status:'official',winner_numbers:[1],source_url:'https://inh.gob.ve/resultados',reviewed_by:'test',reviewed_at:'2026-09-20T18:00:00Z',occurred_at:'2026-09-20T18:00:00Z',race_started_at:'2026-09-20T17:00:00Z'};
const now=new Date('2026-09-21T00:00:00Z');
const first=applyEvent(base,meetings,snapshots,[],now);
assert.equal(model.outcome(rinconada,race,first.events,snapshots).hit,true);
assert.equal(applyEvent(base,meetings,snapshots,first.events,now).duplicate,true);
assert.throws(()=>applyEvent({...base,winner_numbers:[2]},meetings,snapshots,first.events,now),/Correction/);
const corrected=applyEvent({...base,winner_numbers:[2],corrects:first.event.id},meetings,snapshots,first.events,now);
assert.equal(corrected.events.length,2);
assert.equal(model.outcome(rinconada,race,corrected.events,snapshots).hit,false);
assert.throws(()=>applyEvent({...base,source_url:'https://example.com'},meetings,snapshots,[],now),/Official INH/);
assert.throws(()=>applyEvent({...base,status:'provisional'},meetings,snapshots,[],now),/Official winner/);
const corrupt=structuredClone(snapshots);corrupt.find(s=>s.id===rinconada.analysis_snapshot_id).analysis.races[0].horses[0].name='changed';
assert.throws(()=>applyEvent(base,meetings,corrupt,[],now),/integrity/);
const absentTime=structuredClone(snapshots);absentTime.find(s=>s.id===rinconada.analysis_snapshot_id).frozen_at=null;
assert.equal(model.outcome(rinconada,race,first.events,absentTime).hit,null);
assert.equal(model.ticketOutcome(valencia,valencia.tickets[0],[],snapshots),null);
console.log('Chronology, timezone, combinations, provenance, corrections and idempotency tests passed');
