const fs=require('fs'); const path=require('path');
const model=require('../js/jornada-model.js');
const meetings=[...JSON.parse(fs.readFileSync('data/meetings.json')).meetings,...JSON.parse(fs.readFileSync('data/legacy-meetings.json')).meetings];
let template=fs.readFileSync('index.html','utf8').replaceAll('href="assets/','href="/assets/').replaceAll('href="css/','href="/css/').replaceAll('src="js/','src="/js/');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cards=ms=>ms.map(m=>`<article class="card"><p>${esc(m.date)}</p><h2>${esc(m.track)}</h2><a href="/reuniones/${esc(m.slug)}">Consultar jornada</a></article>`).join('');
const fallback=m=>`<div class="wrap section"><h1>${esc(m.track)} · ${esc(m.date)}</h1><p>Pronósticos de Zona Caliente Pro. Horarios sujetos a confirmación.</p>${model.orderedRaces(m).map(r=>`<article class="card"><h2>${esc(r.public_label)} · ${esc(r.time||'Hora pendiente')}</h2><p>${esc(r.distance||'Distancia pendiente')}</p><p>${r.horses.map(h=>`#${esc(h.number)} ${esc(h.name)}`).join(' · ')}</p></article>`).join('')}<h2>Cuadro Perfecto 5y6</h2>${m.tickets.map(t=>`<p>${esc(t.tier)}: ${model.combinations(t.legs)??'Pendiente'} combinaciones.</p>`).join('')}<a href="https://apuestas.inh.gob.ve/" target="_blank" rel="noopener noreferrer">Jugar 5y6 en INH — sitio oficial externo</a><p>Zona Caliente Pro es independiente del INH.</p></div>`;
function write(route,title,content){let html=template.replace(/<title>.*?<\/title>/,`<title>${esc(title)} | Zona Caliente Pro</title>`).replace(/<main id="main"[\s\S]*?<\/main>/,`<main id="main" tabindex="-1" aria-busy="false">${content}</main>`).replace(/<link rel="canonical"[^>]*>/,`<link rel="canonical" href="https://cuadroperfecto.com${route}">`).replace(/<meta property="og:url"[^>]*>/,`<meta property="og:url" content="https://cuadroperfecto.com${route}">`).replace(/<meta property="og:title"[^>]*>/,`<meta property="og:title" content="${esc(title)} | Zona Caliente Pro">`);const file=route==='/'?'index.html':path.join(route.slice(1),'index.html');fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,html);}
write('/reuniones','Calendario y archivo',`<div class="wrap section"><h1>Calendario y archivo</h1>${cards(meetings.slice().sort((a,b)=>a.date.localeCompare(b.date)))}</div>`);
write('/resultados','Historial de resultados',`<div class="wrap section"><h1>Historial de resultados</h1><p>Archivo heredado; las métricas verificadas requieren fuentes oficiales.</p>${cards(meetings.filter(m=>m.results))}</div>`);
write('/estadisticas','Estadísticas',`<div class="wrap section"><h1>Estadísticas de caballos, jinetes y entrenadores</h1><p>Archivo estadístico disponible hasta junio de 2026. Activa JavaScript para filtrar por hipódromo y período.</p></div>`);
const engineFallback=m=>{const e=m.intelligence.engine;const rows=model.orderedRaces(m).map(r=>{const f=r.horses.find(h=>h.role==='FAVORITO_ZCP');return `<tr><th scope="row">${esc(r.public_label)}</th><td>${esc(r.time||'—')}</td><td>${r.selection==='NO_SELECTION'||!f?'NO_SELECTION':'#'+esc(f.number)+' '+esc(f.name)}</td></tr>`;}).join('');return `<div class="wrap section"><h1>${esc(m.track)} · Reunión ${esc(m.meeting_number)} · ${esc(m.date)}</h1><h2>Previa de la jornada</h2><p>${(m.intelligence.alertas||[]).map(esc).join('<br>')}</p><h2>Favoritos H2 v1.1</h2><p>${esc(e.label)}</p><p>${esc(e.explanation)}</p><p>Gate: ${esc(e.gate)}. ${esc(e.scope)}</p><div class="table-scroll"><table><thead><tr><th>Carrera</th><th>Hora</th><th>Favorito público</th></tr></thead><tbody>${rows}</tbody></table></div><p>Modelo ${esc(e.model)} · commit ${esc(e.commit)} · pronóstico congelado: ${esc(m.analysis_snapshot_id)}.</p><h2>Retirados oficiales</h2><ul>${(m.intelligence.retirados||[]).map(x=>'<li>'+esc(x)+'</li>').join('')}</ul><h2>Análisis carrera por carrera</h2>${model.orderedRaces(m).map(r=>`<article class="card"><h3>${esc(r.public_label)} · ${esc(r.time||'Hora pendiente')} · ${esc(r.distance||'')}</h3><p>${esc(r.analysis||'')}</p></article>`).join('')}<h2>Contenido editorial Zona Caliente Pro</h2><p>${e.editorial?esc(e.editorial):'Pendiente de publicación; irá rotulado como «Selección editorial Zona Caliente Pro».'}</p><h2>Cuadro Perfecto 5y6</h2><p>${esc(e.five_six)}</p><a href="https://apuestas.inh.gob.ve/" target="_blank" rel="noopener noreferrer">Sitio oficial del INH — externo</a><p>${esc(e.disclaimer)}</p><p>Zona Caliente Pro es independiente del INH.</p></div>`;};
for(const m of meetings)write('/reuniones/'+m.slug,m.track+' '+m.date,m.intelligence?.engine?engineFallback(m):fallback(m));
for(const [route,track] of [['/valencia','Valencia'],['/rinconada','La Rinconada'],['/la-rinconada','La Rinconada']]){const m=require('../js/meeting-selection.js').selectCurrentMeeting(meetings.filter(x=>x.track===track));if(m)write(route,track,m.intelligence?.engine?engineFallback(m):fallback(m));}
const homeResult=`<section class="result-hero" aria-labelledby="balance-title"><div class="result-copy"><p class="eyebrow">Balance verificado · 26 y 27 de septiembre</p><h1 id="balance-title">El boleto sellado cubrió 5 de 6</h1><p class="result-lead">Una buena lectura no siempre termina en rentabilidad. Separamos el rendimiento de nuestros cuadros del boleto personal jugado para mostrar el resultado completo, sin mezclar cifras.</p><div class="result-summary"><article><strong>3/6</strong><span>Valencia R24<br>cuadro presentado</span></article><article><strong>1/6</strong><span>La Rinconada R38<br>cuadro recomendado · 96 combinaciones</span></article><article class="result-highlight"><strong>5/6</strong><span>Boleto personal sellado<br>162 combinaciones</span></article></div><p class="result-money"><span>Premio <strong>Bs. 3.158,18</strong></span><span>Costo <strong>Bs. 5.670</strong></span></p><p class="result-note">En la octava carrera de R38, la selección registrada fue <strong>#7 Grand Gala</strong>. El acierto se comunica con orgullo; la rentabilidad, con transparencia.</p><div class="hero-actions"><a class="btn btn-inh" href="https://apuestas.inh.gob.ve/" target="_blank" rel="noopener noreferrer">Jugar 5Y6 en el INH ↗</a><a class="hero-link" href="/resultados">Ver historial verificado</a></div><small class="independence">Portal oficial externo. Cuadro Perfecto es independiente y no está afiliado al INH.</small></div><figure><img src="/assets/publications/balance-26-27-septiembre-2026.webp" width="900" height="1125" loading="eager" fetchpriority="high" alt="Infografía del boleto sellado con cinco aciertos de seis y balances separados de Valencia y La Rinconada"><figcaption>Balance editorial de las jornadas del sábado 26 y domingo 27.</figcaption></figure></section>`;
const homeVision=`<section class="home-vision" aria-labelledby="vision-title"><div><p class="eyebrow">La visión correcta</p><h2 id="vision-title">Análisis antes. Evidencia después.</h2><p>No vendemos certezas. Publicamos selecciones, conservamos el pronóstico original y confrontamos cada jornada con el resultado real.</p></div><div class="vision-grid"><article><b>01</b><h3>Leer la carrera</h3><p>Forma, trabajos, conexiones y contexto de cada ejemplar.</p></article><article><b>02</b><h3>Construir el cuadro</h3><p>Coberturas diferenciadas, combinaciones claras y costo visible.</p></article><article><b>03</b><h3>Rendir cuentas</h3><p>Aciertos y fallos separados del boleto finalmente sellado.</p></article></div></section>`;
const recent=meetings.slice().sort((a,b)=>b.date.localeCompare(a.date)).slice(0,6);
const engineMeeting=meetings.filter(m=>m.intelligence?.engine).sort((a,b)=>b.date.localeCompare(a.date))[0];
const homeEngine=engineMeeting?`<section class="home-archive" aria-labelledby="h2-title"><div class="section-heading"><div><p class="eyebrow">${esc(engineMeeting.intelligence.engine.label)}</p><h2 id="h2-title">${esc(engineMeeting.track)} · Reunión ${esc(engineMeeting.meeting_number)} · domingo 4 de octubre</h2></div><a href="/reuniones/${esc(engineMeeting.slug)}">Ver la jornada completa →</a></div><p>${esc(engineMeeting.intelligence.engine.explanation)}</p><div class="archive-grid">${model.orderedRaces(engineMeeting).map(r=>{const f=r.horses.find(h=>h.role==='FAVORITO_ZCP');return `<article class="card"><p>${esc(r.public_label)} · ${esc(r.time||'')}</p><h3>${r.selection==='NO_SELECTION'||!f?'NO_SELECTION':'#'+esc(f.number)+' '+esc(f.name)}</h3></article>`;}).join('')}</div><p>Retirados oficiales: ${(engineMeeting.intelligence.retirados||[]).map(esc).join(' · ')}</p><p><small>${esc(engineMeeting.intelligence.engine.disclaimer)}</small></p></section>`:'';
write('/','Jornadas de Valencia y La Rinconada',`<div class="wrap section">${homeEngine}${homeResult}${homeVision}<section class="home-archive" aria-labelledby="archive-title"><div class="section-heading"><div><p class="eyebrow">Archivo abierto</p><h2 id="archive-title">Jornadas recientes</h2></div><a href="/reuniones">Ver todo el calendario →</a></div><div class="archive-grid">${cards(recent)}</div></section><section class="home-cta"><p class="eyebrow">ZONA CALIENTE PRO</p><h2>Pronósticos que no desaparecen después de la carrera.</h2><p>Consulta el análisis, revisa el historial y juega con responsabilidad.</p><div><a class="btn" href="/reuniones">Consultar jornadas</a><a href="https://t.me/LaRectaCaliente" target="_blank" rel="noopener noreferrer">Seguir en Telegram ↗</a></div></section></div>`);
const routes=['/','/reuniones','/resultados','/estadisticas',...meetings.map(m=>'/reuniones/'+m.slug)];fs.writeFileSync('sitemap.xml','<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+routes.map(r=>`<url><loc>https://cuadroperfecto.com${r}</loc></url>`).join('')+'</urlset>');
console.log('Generated static, directly accessible pages:',routes.length+3);
