const fs=require('fs'); const path=require('path');
const model=require('../js/jornada-model.js');
const meetings=[...JSON.parse(fs.readFileSync('data/meetings.json')).meetings,...JSON.parse(fs.readFileSync('data/legacy-meetings.json')).meetings];
let template=fs.readFileSync('index.html','utf8').replaceAll('href="assets/','href="/assets/').replaceAll('href="css/','href="/css/').replaceAll('src="js/','src="/js/');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cards=ms=>ms.map(m=>`<article class="card"><p>${esc(m.date)}</p><h2>${esc(m.track)}</h2><a href="/reuniones/${esc(m.slug)}">Consultar jornada</a></article>`).join('');
const fallback=m=>`<div class="wrap section"><h1>${esc(m.track)} · ${esc(m.date)}</h1><p>Pronósticos de Zona Caliente Pro. Horarios sujetos a confirmación.</p>${model.orderedRaces(m).map(r=>`<article class="card"><h2>${esc(r.public_label)} · ${esc(r.time||'Hora pendiente')}</h2><p>${esc(r.distance||'Distancia pendiente')}</p><p>${r.horses.map(h=>`#${esc(h.number)} ${esc(h.name)}`).join(' · ')}</p></article>`).join('')}<h2>Cuadro Perfecto 5y6</h2>${m.tickets.map(t=>`<p>${esc(t.tier)}: ${model.combinations(t.legs)??'Pendiente'} combinaciones.</p>`).join('')}<a href="https://apuestas.inh.gob.ve/" target="_blank" rel="noopener noreferrer">Jugar 5y6 en INH — sitio oficial externo</a><p>Zona Caliente Pro es independiente del INH.</p></div>`;
function write(route,title,content){let html=template.replace(/<title>.*?<\/title>/,`<title>${esc(title)} | Zona Caliente Pro</title>`).replace(/<main id="main"[\s\S]*?<\/main>/,`<main id="main" tabindex="-1" aria-busy="false">${content}</main>`).replace(/<link rel="canonical"[^>]*>/,`<link rel="canonical" href="https://cuadroperfecto.com${route}">`).replace(/<meta property="og:url"[^>]*>/,`<meta property="og:url" content="https://cuadroperfecto.com${route}">`).replace(/<meta property="og:title"[^>]*>/,`<meta property="og:title" content="${esc(title)} | Zona Caliente Pro">`);const file=route==='/'?'index.html':path.join(route.slice(1),'index.html');fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,html);}
write('/reuniones','Calendario y archivo',`<div class="wrap section"><h1>Calendario y archivo</h1>${cards(meetings.slice().sort((a,b)=>a.date.localeCompare(b.date)))}</div>`);
write('/resultados','Historial de resultados',`<div class="wrap section"><h1>Historial de resultados</h1><p>Archivo heredado; las métricas verificadas requieren fuentes oficiales.</p>${cards(meetings.filter(m=>m.results))}</div>`);
write('/estadisticas','Estadísticas',`<div class="wrap section"><h1>Estadísticas de caballos, jinetes y entrenadores</h1><p>Archivo estadístico disponible hasta junio de 2026. Activa JavaScript para filtrar por hipódromo y período.</p></div>`);
for(const m of meetings)write('/reuniones/'+m.slug,m.track+' '+m.date,fallback(m));
for(const [route,track] of [['/valencia','Valencia'],['/rinconada','La Rinconada'],['/la-rinconada','La Rinconada']]){const m=require('../js/meeting-selection.js').selectCurrentMeeting(meetings.filter(x=>x.track===track));if(m)write(route,track,fallback(m));}
write('/','Jornadas de Valencia y La Rinconada',`<div class="wrap section"><h1>Jornadas de Valencia y La Rinconada</h1><p>Consulta el programa y los pronósticos por fecha.</p>${cards(meetings.filter(m=>m.status!=='FINALIZADA').sort((a,b)=>a.date.localeCompare(b.date)))}</div>`);
const routes=['/','/reuniones','/resultados','/estadisticas',...meetings.map(m=>'/reuniones/'+m.slug)];fs.writeFileSync('sitemap.xml','<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+routes.map(r=>`<url><loc>https://cuadroperfecto.com${r}</loc></url>`).join('')+'</urlset>');
console.log('Generated static, directly accessible pages:',routes.length+3);
